<?xml version="1.0"?>
<package format="3">
  <name>draw_10</name>
  <version>0.0.1</version>
  <description>Draw variant 10 with two turtlesim turtles and pose feedback.</description>
  <maintainer email="235694859+markpspsn@users.noreply.github.com">Arseniy Mukhometov</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>turtlesim</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
